# Variables and variable types

## "Regular" variables

1. strings
1. integers
1. floats

## "Collection" variables

1. tuples
1. lists
1. sets
1. dictionaries

From https://www.w3schools.com:

- **Strings** are for storing text
- **Integers** are for storing whole numbers, positive or negative (such as 123 or -456), without decimals.
- **Floats** are for storing positive and negative numbers with a decimal point, like 35.3, or -2.34
- **Lists** are collections which are ordered and changeable. Allows duplicate members.
- **Tuples** are collections which are ordered and unchangeable. Allows duplicate members.
- **Sets** are collections which are unordered, "unchangeable", and unindexed. No duplicate members.
- **Dictionaries** are collections which are ordered and changeable. No duplicate members.

## Strings

In [17]:
today = "friday"
type(today)

str

## Integers

In [18]:
week = 37
type(week)

int

## Floats

In [19]:
time = 8.5
type(time)

float

## Lists

In [20]:
myVariables = [3, 2, 78, 2]

lists are ordered and so we can call items from their ordered position

In [21]:
myVariables[1]

2

python counts from 0 (jst like stories in a house). some programming Lscounts from 1

In [22]:
myVariables[0]

3

you can also change the items of the list

In [23]:
myVariables[1]=5
myVariables

[3, 5, 78, 2]

In [24]:
yourVariables = [today, week, time]
yourVariables

['friday', 37, 8.5]

In [25]:
yourVariables

['friday', 37, 8.5]

## Tuples

In [26]:
shopping_list = ["apples", "pears", "bananas"]
shopping_tuple = ("apples", "pears", "bananas")

In [27]:
shopping_list[1]

'pears'

In [28]:
shopping_list[2]

'bananas'

In [29]:
shopping_list[1] = "grapes"
shopping_list

['apples', 'grapes', 'bananas']

In [30]:
shopping_tuple[1] = "grapes"
shopping_tuple

TypeError: 'tuple' object does not support item assignment

you get an error bc tuples are unchangeable

## Sets

In [31]:
newList = [4, 4, 7, 19, 21, "im a string", "aa", 7.23]
mySet = set(newList)
mySet

{19, 21, 4, 7, 7.23, 'aa', 'im a string'}

sets are unordered, and can have no duplicate members. python seems to order sets by lowest number and then alphabet (21 is lower than four bc python looks at 2 vs. 4).

the len() counts the number of items.

you can also make sets like this:

In [32]:
myNextSet = {3, 5, 7}
myNextSet

{3, 5, 7}

## Dictionaries

In [33]:
my_pet = {'name': 'D2',
         'species': 'cat',
         'likes': 'sleeping',
         'dislikes': 'loud noises',
         'age': 10}

here items are separated by a colon: {key:value}

In [34]:
my_pet["age"]

10

In [35]:
my_pet["likes"]

'sleeping'

In [36]:
items = ['grapes', 'skyr', 'milk', 'rice']
number = [1, 2, 7, 3]
priority = ['high', 'high', 'low', 'high']

In [37]:
shopping = {'items': items,
            'number': number,
            'priority': priority}

In [38]:
shopping['items']

['grapes', 'skyr', 'milk', 'rice']

In [39]:
shopping['items'] [2]

'milk'

you can also make lists inside lists. this embedded list will also count as an item.

In [40]:
body = [['sweater', 'tshirt'], 'jeans', ['socks', 'shoes']]
head = ['curls', 'bobby pins']
hands = ['rings', 'bracelet']

In [41]:
outfit = {'clothes': clothes,
          'hair': hair,
          'accessories': accessories}

NameError: name 'clothes' is not defined

In [42]:
outfit['accessories']
#here I get python to show me the list connected to 'hands'

NameError: name 'outfit' is not defined

In [43]:
outfit['clothes'][0][0]
#here I get python to show me the first item in the first embedded item

NameError: name 'outfit' is not defined

## function len()

In [44]:
a = [4, 5, 6, 7, 8, 9, 10, 55]

In [45]:
type(a)

list

In [46]:
len(a)

8

In [47]:
b = 'i am a string!'
len(b)

14

slicing:

In [48]:
a[3:5]

[7, 8]

In [49]:
a[3:]

[7, 8, 9, 10, 55]

negative indexing: when you count the places in the list from the end, so:

In [50]:
a[-1]

55

-1 is the last item on the list

## dataframes

there exists this package/module/library called pandas.

it is not part of the standard python-library.

we can install this module on our computer, and then we can import the library in to all our files.

so, you don't need to install it every time, but you need to import it for every new file you make.

(pandas is already installed in jupyter tho)

In [51]:
import pandas as pd

"as pd" assigns a name for pandas that we have decided on.

pd is the standard shortened version for pandas, so use that.

making a dataframe:

In [52]:
a = [3, 4, 78, 6]
b = [43, 42, 178, 76]
c = [38, 45, 728, 46]

pandas insist upon having equal rows and columns in a dataframe

In [53]:
arla = pd.DataFrame({'a': a, 'b': b,'c': c})

.DataFrame is a function that pandas has

In [54]:
type(arla)

pandas.DataFrame

In [55]:
arla

    a    b    c
0   3   43   38
1   4   42   45
2  78  178  728
3   6   76   46

getting our data out again:

In [56]:
arla['a']

0     3
1     4
2    78
3     6
Name: a, dtype: int64

In [57]:
d = arla['a'] #now we also define the a-column as a pandas-series
type(d)

pandas.Series

In [58]:
e = list(d)
e

[3, 4, 78, 6]

In [59]:
a == e #the double equal signs compares the two things

True

section 7.5.2 in LSP book is about dataframes

In [71]:
arla['row_mean'] = arla.mean(axis=1) 
#this function calculates the mean of every row.
#axis=1 means calculates row by row

In [62]:
arla

    a    b    c    row_mean
0   3   43   38   28.000000
1   4   42   45   30.333333
2  78  178  728  328.000000
3   6   76   46   42.666667

In [75]:
#name = pd.read_csv('/work/pathofCSVfileyouwanttoread')

In [92]:
df = pd.read_csv('/work/Experimental-Psycholinguistics-hello-Ethan-/Stroop-raw-over-the-years.csv')

In [97]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0             4.16        6.76          4.45         4.65  2015
1             4.35        7.73          4.78         4.46  2015
2             3.60        7.00          4.00         3.50  2015
3             3.90        9.03          4.60         6.30  2015
4             4.22        9.98          6.83         6.24  2015
..             ...         ...           ...          ...   ...
200           4.77       10.00          5.66         6.24  2025
201           4.61       12.80          6.87         9.55  2025
202           4.79       10.72          5.64         7.25  2025
203           4.41        8.87          6.70         6.70  2025
204           5.50        9.80          6.20        21.70  2025

[205 rows x 5 columns]

In [98]:
df = df.drop(['Year'],axis=1)
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int
0             4.16        6.76          4.45         4.65
1             4.35        7.73          4.78         4.46
2             3.60        7.00          4.00         3.50
3             3.90        9.03          4.60         6.30
4             4.22        9.98          6.83         6.24
..             ...         ...           ...          ...
200           4.77       10.00          5.66         6.24
201           4.61       12.80          6.87         9.55
202           4.79       10.72          5.64         7.25
203           4.41        8.87          6.70         6.70
204           5.50        9.80          6.20        21.70

[205 rows x 4 columns]

In [100]:
df['MeanRT'] = df.mean(axis=1)
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int   MeanRT
0             4.16        6.76          4.45         4.65   5.0050
1             4.35        7.73          4.78         4.46   5.3300
2             3.60        7.00          4.00         3.50   4.5250
3             3.90        9.03          4.60         6.30   5.9575
4             4.22        9.98          6.83         6.24   6.8175
..             ...         ...           ...          ...      ...
200           4.77       10.00          5.66         6.24   6.6675
201           4.61       12.80          6.87         9.55   8.4575
202           4.79       10.72          5.64         7.25   7.1000
203           4.41        8.87          6.70         6.70   6.6700
204           5.50        9.80          6.20        21.70  10.8000

[205 rows x 5 columns]

In [101]:
df_sorted = df.sort_values(by=['Reading_NoInt'])

In [102]:
df_sorted

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int   MeanRT
77            2.83        6.29          4.03         4.15   4.3250
148           2.85        9.64          5.80         4.91   5.8000
149           2.93        7.40          5.28         3.28   4.7225
99            3.02        7.01          4.59         3.63   4.5625
10            3.10       10.49          5.34         3.62   5.6375
..             ...         ...           ...          ...      ...
120           7.06       12.44          8.15        11.85   9.8750
168           7.07        6.88          5.50         6.45   6.4750
191           7.31       28.32         24.62         7.46  16.9275
123           7.35        9.84          4.78         4.78   6.6875
115           8.16       12.33         11.71         7.23   9.8575

[205 rows x 5 columns]

In [85]:
from statistics import mean
df['meanRT'] = mean(df['Reading_NoInt', 'Naming_Int', 'Naming_NoInt', 'Reading_In'])

KeyError: ('Reading_NoInt', 'Naming_Int', 'Naming_NoInt', 'Reading_In')